name: mohit_portfolio
description: "A new Flutter portfolio web app using MVVM architecture."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.5

  # UI Enhancements
  google_fonts: ^6.2.1
  flutter_animate: ^4.2.0
  url_launcher: ^6.2.6

  # Image Handling
  cached_network_image: ^3.3.1

  # Icon Packs
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  web: ^1.1.1
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/certifications/
    - assets/images/
    - assets/services_cards/
    - assets/projects/
    - assets/icons/

  # Optional: Add fonts section if using custom fonts manually (skip if using google_fonts)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
